[project]
name = "aprendizaje-automatico"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["pandas>=2.3.2", "pandas-stubs>=2.3.2.250827"]

[tool.basedpyright]
typeCheckingMode = "standard"
